[auth]
 enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []
 jwt_expiry = 3600
 enable_refresh_token_rotation = true
 refresh_token_reuse_interval = 10

 [auth.email]
 enable_signup = true
 double_confirm_changes = true
enable_confirmations = true
 secure_password_change = false
max_frequency = "1m0s"
 otp_length = 6
 otp_expiry = 3600
 [auth.email.template]
[functions.add-to-watchlist]
enabled = true
verify_jwt = true
import_map = "./functions/add-to-watchlist/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/add-to-watchlist/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/add-to-watchlist/*.html" ]

[functions.get-watchlist-status]
enabled = true
verify_jwt = true
import_map = "./functions/get-watchlist-status/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-watchlist-status/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-watchlist-status/*.html" ]
